---
- hosts: intranet
  become: true

  tasks:
    - name: 'Instalar pacotes de dependência do sistema operacional'
      become: yes
      apt:
        pkg:
          - php7.0
          - php-pear
          - php7.0-curl
          - php7.0-gd
          - php7.0-intl
          - php7.0-xmlrpc
          - php7.0-mysql
          - apache2
          - python-mysqldb
          - wget
          - zip
          - curl
          - vim
        state: present  